export const TICK_RATE = 20;
export const WORLD_SIZE = 100;
export const PLAYER_SPEED = 12;
export const PLAYER_SPRINT_MULTIPLIER = 1.7;
export const TILE_SIZE = 2;

export const WEAPON_SLOTS = ['pistol', 'rifle', 'uzi', 'shotgun'];

export const WEAPONS = {
  pistol: {
    name: 'Pistol',
    damage: 20,
    fireRate: 0.3,
    magazine: 12,
    reloadTime: 1.5,
    projectileSpeed: 40,
    range: 30,
    pellets: 1,
    spreadAngle: 0,
    damageFalloff: true,
    falloffStart: 15,
    falloffMinMult: 0.5,
    laserLength: 5,
    laserColor: 0xff3333,
    coneMaxSpread: 2,
    coneMinSpread: 0.04,
    focusDuration: 0.8,
    hotkey: 1,
  },
  rifle: {
    name: 'Rifle',
    damage: 35,
    fireRate: 0.8,
    magazine: 8,
    reloadTime: 2.5,
    projectileSpeed: 60,
    range: 80,
    pellets: 1,
    spreadAngle: 0,
    damageFalloff: false,
    falloffStart: 0,
    falloffMinMult: 1.0,
    laserLength: 50,
    laserColor: 0x33ff33,
    coneMaxSpread: 0.8,
    coneMinSpread: 0.02,
    focusDuration: 1.5,
    hotkey: 2,
  },
  uzi: {
    name: 'Uzi',
    damage: 10,
    fireRate: 0.1,
    magazine: 30,
    reloadTime: 1.8,
    projectileSpeed: 35,
    range: 20,
    pellets: 1,
    spreadAngle: 0,
    damageFalloff: true,
    falloffStart: 10,
    falloffMinMult: 0.6,
    laserLength: 3.5,
    laserColor: 0xff8833,
    coneMaxSpread: 3,
    coneMinSpread: 0.08,
    focusDuration: 0.4,
    hotkey: 3,
  },
  shotgun: {
    name: 'Shotgun',
    damage: 8,
    fireRate: 1.0,
    magazine: 6,
    reloadTime: 2.2,
    projectileSpeed: 30,
    range: 12,
    pellets: 6,
    spreadAngle: 0.35,
    damageFalloff: true,
    falloffStart: 5,
    falloffMinMult: 0.3,
    laserLength: 2.5,
    laserColor: 0xff4411,
    coneMaxSpread: 5,
    coneMinSpread: 0.3,
    focusDuration: 0.6,
    hotkey: 4,
  },
};
